language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
  - tar xf arduino-1.8.1-linux64.tar.xz
  - sudo mv arduino-1.8.1 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/DCF77
  - arduino --install-library "Time"
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/DCFBinaryStream/DCFBinaryStream.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/DCFPulseLength/DCFPulseLength.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/DCFSignal/DCFSignal.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/InternalClockSync/InternalClockSync.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/SyncProvider/SyncProvider.ino  
notifications:
  email:
    on_success: change
    on_failure: change
